(function (root, factory) {
  const api = factory();
  if (typeof module === "object" && module.exports) module.exports = api;
  root.AiMonopolyRules = api;
})(typeof globalThis !== "undefined" ? globalThis : window, function () {
const initialMetrics = {
  cash: 10000,
  users: 0,
  product: 1,
  tech: 1,
  reputation: 1,
  compliance: 1,
};

const metricLabels = {
  cash: "现金",
  users: "用户",
  product: "产品力",
  tech: "技术力",
  reputation: "声誉",
  compliance: "合规",
};

const roleLabels = {
  ceo: "CEO / 产品",
  cto: "CTO / 技术",
  cmo: "CMO / 运营",
  cfo: "CFO / 风控",
};

const scoreItems = [
  ["demo", "AI 项目完成度与演示", 25],
  ["tech", "技术实现与课程知识应用", 20],
  ["market", "用户需求、MVP 与商业验证", 15],
  ["process", "课中经营累计表现", 10],
  ["finalGame", "期末大富翁决战表现", 15],
  ["teamwork", "答辩表达与团队协作", 10],
  ["compliance", "合规与反思", 5],
];

const boardCells = [
  ["起点", "公司进入期末路演", "start"],
  ["产品格", "说明目标用户和核心痛点", "product"],
  ["技术格", "说明 Agent 或 Bot 的工作机制", "tech"],
  ["机会格", "抽 1 张机会卡", "opportunity"],
  ["市场格", "说明竞品和差异化", "market"],
  ["风险格", "回答隐私、伦理或版权问题", "risk"],
  ["演示格", "演示核心功能", "demo"],
  ["资本格", "进行 1 分钟融资陈述", "capital"],
  ["危机格", "抽 1 张危机卡", "crisis"],
  ["产品格", "说明 MVP 取舍", "product"],
  ["技术格", "展示 Workflow 或流程图", "tech"],
  ["复盘格", "说明一次失败决策和改进", "review"],
  ["机会格", "抽 1 张机会卡", "opportunity"],
  ["市场格", "说明用户增长策略", "market"],
  ["风险格", "回答模型幻觉或错误输出处理", "risk"],
  ["演示格", "演示一次真实使用场景", "demo"],
  ["资本格", "回答商业模式问题", "capital"],
  ["危机格", "抽 1 张危机卡", "crisis"],
  ["产品格", "说明版本迭代依据", "product"],
  ["技术格", "说明 Prompt 优化或知识库设计", "tech"],
  ["市场格", "说明用户反馈如何改变产品", "market"],
  ["风险格", "回答数据安全和授权问题", "risk"],
  ["复盘格", "说明团队分工和协作问题", "review"],
  ["决战格", "进入最终投资人路演", "final"],
].map(([title, task, type], index) => ({ index, title, task, type }));

const strategies = [
  {
    id: "interview",
    name: "用户访谈",
    role: "cmo",
    cost: -500,
    success: { product: 1, reputation: 1 },
    partial: { product: 1 },
    fail: {},
    note: "提交访谈问题和结论。",
  },
  {
    id: "competitor",
    name: "竞品分析",
    role: "ceo",
    cost: -800,
    success: { product: 1, cash: 1000 },
    partial: { product: 1 },
    fail: {},
    note: "说明 2 个竞品和差异化。",
  },
  {
    id: "prompt",
    name: "Prompt 优化",
    role: "cto",
    cost: -800,
    success: { tech: 1 },
    partial: {},
    fail: {},
    note: "展示优化前后的变化。",
  },
  {
    id: "workflow",
    name: "工作流重构",
    role: "cto",
    cost: -1500,
    success: { tech: 2, product: 1 },
    partial: { tech: 1 },
    fail: {},
    note: "展示流程图或关键节点。",
  },
  {
    id: "knowledge",
    name: "接入知识库",
    role: "cto",
    cost: -2000,
    success: { tech: 2 },
    partial: { tech: 1 },
    fail: { compliance: -1 },
    note: "说明数据来源和使用方式，合规低时需谨慎。",
  },
  {
    id: "demo",
    name: "快速 Demo",
    role: "cto",
    cost: -1500,
    success: { product: 2 },
    partial: { product: 1 },
    fail: {},
    note: "展示原型、流程或可运行版本。",
  },
  {
    id: "ads",
    name: "广告投放",
    role: "cmo",
    cost: -2500,
    success: { users: 50 },
    partial: { users: 20 },
    fail: { reputation: -1 },
    note: "产品力低于 3 时，失败概率较高。",
  },
  {
    id: "pilot",
    name: "校园试点",
    role: "cmo",
    cost: -1000,
    success: { users: 30, reputation: 1 },
    partial: { users: 10 },
    fail: {},
    note: "说明真实使用场景。",
  },
  {
    id: "partner",
    name: "商业合作",
    role: "cfo",
    cost: -1500,
    success: { cash: 4000 },
    partial: { cash: 1000 },
    fail: {},
    note: "讲清合作对象和收益逻辑。",
  },
  {
    id: "paid-pilot",
    name: "校园小额付费试点",
    role: "cmo",
    group: "基础变现",
    cost: -500,
    success: { cash: 1500, users: 10 },
    partial: { cash: 500, users: 5 },
    fail: {},
    disabled: (team) => team.metrics.product < 2,
    note: "产品力至少为 2；适合前期验证真实付费意愿。",
  },
  {
    id: "prompt-pack",
    name: "模板/提示词包售卖",
    role: "cto",
    group: "基础变现",
    cost: -300,
    success: { cash: 1200 },
    partial: { cash: 400 },
    fail: {},
    disabled: (team) => team.metrics.tech < 2,
    note: "技术力至少为 2；把已有能力包装成可交付小产品。",
  },
  {
    id: "sponsor",
    name: "社群内测赞助",
    role: "cmo",
    group: "基础变现",
    cost: -500,
    success: { cash: 1800, reputation: 1 },
    partial: { cash: 600 },
    fail: { reputation: -1 },
    disabled: (team) => team.metrics.reputation < 2,
    note: "声誉至少为 2；适合有一定口碑后尝试。",
  },
  {
    id: "trial",
    name: "免费试用",
    role: "cmo",
    cost: -1000,
    success: { users: 60 },
    partial: { users: 25 },
    fail: { cash: -500 },
    disabled: (team) => team.metrics.cash < 3000,
    note: "现金低于 3000 时不可选。",
  },
  {
    id: "subscription",
    name: "订阅制试运营",
    role: "cfo",
    group: "增长变现",
    cost: -1000,
    success: { cash: 4000 },
    partial: { cash: 1500 },
    fail: { reputation: -1 },
    note: "需要说清收费对象、价格和续费理由；产品力低时风险较高。",
  },
  {
    id: "custom-demo",
    name: "企业定制 Demo",
    role: "cto",
    group: "增长变现",
    cost: -2000,
    success: { cash: 6000, reputation: 1 },
    partial: { cash: 2000 },
    fail: { cash: -1000 },
    disabled: (team) => team.metrics.tech < 3,
    note: "技术力至少为 3；需要展示可定制能力。",
  },
  {
    id: "campus-procurement",
    name: "校园部门采购",
    role: "cfo",
    group: "增长变现",
    cost: -1500,
    success: { cash: 5000 },
    partial: { cash: 1500 },
    fail: { compliance: -1 },
    disabled: (team) => team.metrics.compliance < 3,
    note: "合规至少为 3；需要说明采购场景、预算和责任边界。",
  },
  {
    id: "co-marketing",
    name: "联名推广分成",
    role: "cmo",
    group: "增长变现",
    cost: -1000,
    success: { cash: 3500, users: 40 },
    partial: { cash: 1200, users: 15 },
    fail: {},
    note: "适合已有目标用户和合作渠道的小组。",
  },
  {
    id: "audit",
    name: "合规审查",
    role: "cfo",
    cost: -1000,
    success: { compliance: 2 },
    partial: { compliance: 1 },
    fail: {},
    note: "短期无收入，但可抵御风险。",
  },
  {
    id: "seed-round",
    name: "种子轮融资",
    role: "ceo",
    group: "高风险融资",
    cost: -1000,
    success: { cash: 10000 },
    partial: { cash: 3000 },
    fail: { reputation: -1 },
    note: "需要 1 分钟讲清市场、产品和增长逻辑。",
  },
  {
    id: "industry-bid",
    name: "行业解决方案竞标",
    role: "cfo",
    group: "高风险融资",
    cost: -3000,
    success: { cash: 12000, reputation: 1 },
    partial: { cash: 3000 },
    fail: { cash: -2000 },
    disabled: (team) => team.metrics.tech < 3 || team.metrics.compliance < 3,
    note: "技术力和合规至少为 3；适合后期成熟项目。",
  },
  {
    id: "paid-api",
    name: "付费 API 服务上线",
    role: "cto",
    group: "高风险融资",
    cost: -2500,
    success: { cash: 8000 },
    partial: { cash: 2000 },
    fail: { reputation: -2 },
    disabled: (team) => team.metrics.tech < 4,
    note: "技术力至少为 4；重点考察稳定性和调用成本。",
  },
  {
    id: "data-partner",
    name: "数据服务合作",
    role: "cfo",
    group: "高风险融资",
    cost: -2000,
    success: { cash: 7000 },
    partial: { cash: 1500 },
    fail: { cash: -3000, compliance: -2 },
    disabled: (team) => team.metrics.compliance < 4,
    note: "合规至少为 4；必须讲清数据来源、授权和使用边界。",
  },
  {
    id: "iteration",
    name: "版本迭代",
    role: "ceo",
    cost: -1500,
    success: { product: 1, tech: 1 },
    partial: { product: 1 },
    fail: {},
    note: "展示前后变化。",
  },
];

const quickActions = [
  ["基础概念正确", { cash: 500 }, "回答基础概念正确"],
  ["结合本组项目", { cash: 1000 }, "回答能结合本组项目"],
  ["有案例和判断", { cash: 1500 }, "回答有案例、有判断、有反思"],
  ["现场演示成功", { product: 1, tech: 1 }, "现场演示成功"],
  ["主动指出风险", { compliance: 1 }, "主动指出数据、伦理或安全风险"],
  ["有价值建议", { reputation: 1 }, "给其他小组提出有价值建议"],
  ["阶段任务迟交", { cash: -1000 }, "阶段任务迟交"],
  ["项目无进展", { product: -1 }, "项目长期无明显进展"],
  ["材料造假", { cash: -3000, reputation: -2, compliance: -2 }, "数据、截图、用户反馈造假"],
];

const opportunityCards = [
  {
    name: "获得企业试点",
    desc: "产品力 >=4，现金 +5000；否则用户 +20。",
    settle: (team) => (team.metrics.product >= 4 ? { cash: 5000 } : { users: 20 }),
  },
  {
    name: "校园推广成功",
    desc: "用户 +50，声誉 +1。",
    settle: () => ({ users: 50, reputation: 1 }),
  },
  {
    name: "投资人关注",
    desc: "2 分钟讲清商业模式，成功现金 +8000。",
    success: { cash: 8000 },
    fail: {},
  },
  {
    name: "行业数据开放",
    desc: "合规 >=3，技术力 +1，产品力 +1；否则无收益。",
    settle: (team) => (team.metrics.compliance >= 3 ? { tech: 1, product: 1 } : {}),
  },
  {
    name: "用户自传播",
    desc: "声誉 >=4，用户 +80；否则用户 +30。",
    settle: (team) => (team.metrics.reputation >= 4 ? { users: 80 } : { users: 30 }),
  },
  {
    name: "教师推荐资源",
    desc: "可跳过一次危机卡；系统记录为声誉 +1。",
    settle: () => ({ reputation: 1 }),
  },
  {
    name: "找到高频场景",
    desc: "产品力 +2。",
    settle: () => ({ product: 2 }),
  },
  {
    name: "模型效果提升",
    desc: "技术力 +1，声誉 +1。",
    settle: () => ({ tech: 1, reputation: 1 }),
  },
  {
    name: "成本结构优化",
    desc: "CFO 说明降本方案，成功现金 +3000。",
    success: { cash: 3000 },
    fail: {},
  },
  {
    name: "社群试用反馈积极",
    desc: "用户 +40，产品力 +1。",
    settle: () => ({ users: 40, product: 1 }),
  },
  {
    name: "获得合作伙伴",
    desc: "说明合作价值，成功现金 +4000。",
    success: { cash: 4000 },
    fail: {},
  },
  {
    name: "产品定位变清晰",
    desc: "CEO 重新陈述定位，成功产品力 +1，声誉 +1。",
    success: { product: 1, reputation: 1 },
    fail: {},
  },
  {
    name: "技术方案被认可",
    desc: "CTO 说明架构亮点，成功技术力 +2。",
    success: { tech: 2 },
    fail: {},
  },
  {
    name: "低成本获客",
    desc: "CMO 说明渠道策略，成功用户 +60。",
    success: { users: 60 },
    fail: {},
  },
  {
    name: "合规准备充分",
    desc: "合规 +2，并免疫一次合规类处罚。",
    settle: () => ({ compliance: 2 }),
  },
  {
    name: "用户提出关键建议",
    desc: "产品力 +1，并获得一次版本迭代机会。",
    settle: () => ({ product: 1 }),
  },
];

const crisisCards = [
  {
    name: "AI 回答不稳定",
    desc: "CTO 说明 Prompt 或 Workflow 优化方案；失败声誉 -1。",
    success: { tech: 1 },
    fail: { reputation: -1 },
  },
  {
    name: "用户隐私质疑",
    desc: "CFO 说明数据处理方式和边界；失败现金 -3000，合规 -1。",
    success: { compliance: 1 },
    fail: { cash: -3000, compliance: -1 },
  },
  {
    name: "竞品上线同类功能",
    desc: "CEO 说明差异化和取舍；失败用户 -30。",
    success: { product: 1 },
    fail: { users: -30 },
  },
  {
    name: "模型调用成本上涨",
    desc: "CFO 调整商业模式或成本结构；失败现金 -2000。",
    success: { cash: 1000 },
    fail: { cash: -2000 },
  },
  {
    name: "用户不会用",
    desc: "CMO 说明用户教育或产品简化方案；失败产品力 -1。",
    success: { reputation: 1 },
    fail: { product: -1 },
  },
  {
    name: "演示现场失败",
    desc: "CTO 现场补救或解释备用方案；失败声誉 -1。",
    success: {},
    fail: { reputation: -1 },
  },
  {
    name: "数据来源不清",
    desc: "CFO 说明授权、来源和替代方案；失败合规 -2。",
    success: { compliance: 1 },
    fail: { compliance: -2 },
  },
  {
    name: "技术依赖单一平台",
    desc: "CTO 说明替代方案或迁移路径；失败技术力 -1。",
    success: { tech: 1 },
    fail: { tech: -1 },
  },
  {
    name: "功能太多太散",
    desc: "CEO 重新定义 MVP；失败产品力 -1。",
    success: { product: 1 },
    fail: { product: -1 },
  },
  {
    name: "用户反馈不一致",
    desc: "CMO 说明如何筛选有效反馈；失败用户 -20。",
    success: { reputation: 1 },
    fail: { users: -20 },
  },
  {
    name: "团队分工混乱",
    desc: "CEO 说明角色调整方案；失败声誉 -1。",
    success: {},
    fail: { reputation: -1 },
  },
  {
    name: "输出内容有事实错误",
    desc: "CTO 说明校验机制；失败声誉 -1，技术力 -1。",
    success: { tech: 1 },
    fail: { reputation: -1, tech: -1 },
  },
  {
    name: "涉及版权素材",
    desc: "CFO 说明版权处理方案；失败合规 -1。",
    success: { compliance: 1 },
    fail: { compliance: -1 },
  },
  {
    name: "项目场景过宽",
    desc: "CEO 收缩目标用户；失败产品力 -1。",
    success: { product: 1 },
    fail: { product: -1 },
  },
  {
    name: "用户增长停滞",
    desc: "CMO 设计新获客策略；失败用户 -20。",
    success: { users: 20 },
    fail: { users: -20 },
  },
  {
    name: "商业模式不清",
    desc: "CFO 说明收费对象和成本收益；失败现金 -2000。",
    success: { cash: 1000 },
    fail: { cash: -2000 },
  },
];

const propCards = [
  { id: "P01", name: "技术加班卡", desc: "演示失败后可补救一次", effect: { kind: "shield", metric: "reputation", amount: 1, contexts: ["demo", "crisis"] } },
  { id: "P02", name: "用户口碑卡", desc: "抵消一次声誉损失", effect: { kind: "shield", metric: "reputation", amount: 1 } },
  { id: "P03", name: "合规护盾卡", desc: "抵消一次合规处罚", effect: { kind: "shield", metric: "compliance", amount: 1 } },
  { id: "P04", name: "专家顾问卡", desc: "可更换一道评委问题", effect: { kind: "note", contexts: ["manual"] } },
  { id: "P05", name: "追加预算卡", desc: "本轮行动成本减半", effect: { kind: "halvePenalty", metric: "cash" } },
  { id: "P06", name: "投资人引荐卡", desc: "资本格融资额 +3000", effect: { kind: "bonusDelta", contexts: ["capital"], delta: { cash: 3000 } } },
  { id: "P07", name: "产品聚焦卡", desc: "产品格回答成功后额外产品力 +1", effect: { kind: "bonusDelta", contexts: ["product"], delta: { product: 1 } } },
  { id: "P08", name: "应急公关卡", desc: "危机卡失败后惩罚减半", effect: { kind: "halvePenalty", contexts: ["crisis"] } },
  { id: "P09", name: "用户访谈卡", desc: "市场格回答成功后额外用户 +30", effect: { kind: "bonusDelta", contexts: ["market"], delta: { users: 30 } } },
  { id: "P10", name: "架构图卡", desc: "技术格回答时可获得 30 秒准备时间", effect: { kind: "note", contexts: ["tech"] } },
  { id: "P11", name: "复盘加分卡", desc: "复盘格回答成功后声誉 +1", effect: { kind: "bonusDelta", contexts: ["review"], delta: { reputation: 1 } } },
  {
    id: "P12",
    name: "一键迭代卡",
    desc: "可将产品力 +1 或技术力 +1，二选一",
    effect: { kind: "chooseDelta", contexts: ["manual"], options: [{ label: "产品力 +1", delta: { product: 1 } }, { label: "技术力 +1", delta: { tech: 1 } }] },
  },
];

const interactionDecks = {
  coop: [
    {
      name: "联合研发",
      desc: "双方各支付 1000；若两组 CTO 都能说明分工，双方技术力 +1，产品力 +1。",
      self: { cash: -1000, tech: 1, product: 1 },
      target: { cash: -1000, tech: 1, product: 1 },
    },
    {
      name: "交叉内测",
      desc: "两组互为用户并提交反馈，双方用户 +20，产品力 +1。",
      self: { users: 20, product: 1 },
      target: { users: 20, product: 1 },
    },
    {
      name: "渠道互推",
      desc: "双方 CMO 说明互推人群，双方用户 +30，声誉 +1。",
      self: { users: 30, reputation: 1 },
      target: { users: 30, reputation: 1 },
    },
    {
      name: "数据共建",
      desc: "双方 CFO 说明数据边界，双方合规 +1，技术力 +1。",
      self: { compliance: 1, tech: 1 },
      target: { compliance: 1, tech: 1 },
    },
    {
      name: "联合路演",
      desc: "两组说明商业互补关系，双方现金 +2000，声誉 +1。",
      self: { cash: 2000, reputation: 1 },
      target: { cash: 2000, reputation: 1 },
    },
    {
      name: "专家共聘",
      desc: "双方各支付 800，共同解决一个技术或产品问题，双方技术力 +1。",
      self: { cash: -800, tech: 1 },
      target: { cash: -800, tech: 1 },
    },
    {
      name: "场景拼图",
      desc: "两组产品属于同一场景上下游，双方产品力 +1，用户 +20。",
      self: { product: 1, users: 20 },
      target: { product: 1, users: 20 },
    },
    {
      name: "联合用户访谈",
      desc: "两组共同访谈同类用户，双方产品力 +1，声誉 +1。",
      self: { product: 1, reputation: 1 },
      target: { product: 1, reputation: 1 },
    },
  ],
  battle: [
    {
      name: "抢占关键词",
      desc: "发起方用户 +10；目标方若不能说明差异化定位，用户 -10。",
      self: { users: 10 },
      targetFail: { users: -10 },
      defense: "目标方 CMO 用 30 秒说明差异化定位。",
    },
    {
      name: "竞品压价",
      desc: "目标方若不能说明成本结构，下次变现收益视为减少 1000，本系统先记录现金 -1000。",
      self: {},
      targetFail: { cash: -1000 },
      targetSuccess: { reputation: 1 },
      defense: "目标方 CFO 说明成本结构和定价底线。",
    },
    {
      name: "舆情质疑",
      desc: "目标方若没有用户反馈或证据，声誉 -1；防守成功声誉 +1。",
      self: {},
      targetFail: { reputation: -1 },
      targetSuccess: { reputation: 1 },
      defense: "目标方展示用户反馈、测试记录或真实证据。",
    },
    {
      name: "技术挑战",
      desc: "目标方 CTO 回答技术问题；失败技术力 -1，成功技术力 +1。",
      self: {},
      targetFail: { tech: -1 },
      targetSuccess: { tech: 1 },
      defense: "目标方 CTO 解释架构、稳定性或工作流。",
    },
    {
      name: "用户截流",
      desc: "发起方用户 +15；目标方防守失败用户 -15。",
      self: { users: 15 },
      targetFail: { users: -15 },
      defense: "目标方 CMO 说明用户留存或社群运营策略。",
    },
    {
      name: "功能模仿",
      desc: "发起方产品力 +1；目标方若不能说明护城河，声誉 -1。",
      self: { product: 1 },
      targetFail: { reputation: -1 },
      defense: "目标方 CEO 说明差异化、数据壁垒或场景壁垒。",
    },
  ],
  negotiation: [
    {
      name: "共同投标",
      desc: "双方临时组队投标；成功双方现金 +4000，失败双方现金 -1000。",
      successSelf: { cash: 4000 },
      successTarget: { cash: 4000 },
      failSelf: { cash: -1000 },
      failTarget: { cash: -1000 },
    },
    {
      name: "技术授权",
      desc: "发起方向目标方授权技术能力：发起方现金 +2000，目标方现金 -2000、技术力 +1。",
      successSelf: { cash: 2000 },
      successTarget: { cash: -2000, tech: 1 },
      failSelf: {},
      failTarget: {},
    },
    {
      name: "市场换资源",
      desc: "双方自行谈判资源交换；教师确认合理后，发起方用户 +20，目标方现金 +2000。",
      successSelf: { users: 20 },
      successTarget: { cash: 2000 },
      failSelf: {},
      failTarget: {},
    },
    {
      name: "联盟保护",
      desc: "双方本轮不能互相使用商战卡；若共同回答市场问题成功，双方声誉 +1。",
      successSelf: { reputation: 1 },
      successTarget: { reputation: 1 },
      failSelf: {},
      failTarget: {},
    },
  ],
};


  return {
    initialMetrics,
    metricLabels,
    roleLabels,
    scoreItems,
    boardCells,
    strategies,
    quickActions,
    opportunityCards,
    crisisCards,
    propCards,
    interactionDecks,
  };
});
